spring:
  application:
    name: ZUUL-GATEWAY
server:
  port: 8086
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  routes:
    SHOPPING-SERVICE:
      path: /shopping/**
      serviceId: SHOPPING-SERVICE
      stripPrefix: true