spring:
  application:
    name: SHOPPING-SERVICE
server:
  port: 9093
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka